---
# Debian 10 Buster no longer ships MongoDB, add repo
- name: Add APT key for MongoDB repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 58712A2291FA4AD5
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Add MongoDB APT repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main
    state: present
    filename: mongodb
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Install MongoDB package
  apt:
    name: "mongodb-org"
    state: latest
    install_recommends: no
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Add lecomte.at APT repository
  apt_repository:
    repo: deb [trusted=yes arch=amd64] http://apt.lecomte.at/repacks/debian/ buster ubiquiti
    state: present
    filename: buster-repacks-ubiquiti
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Install Unifi package
  apt:
    name:
      - openjdk-8-jre-headless
      - unifi
    state: latest
    install_recommends: no
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'
